apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-u5fb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tqxk-tenant/rhtap-demo-app/hacbs-test-project-u5fb@sha256:84f6fd0afc990ab8ec687a8ca7e735d1a3c6491193413fa5cd72c8ff2d23c720
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
